### ISSUE TITLE
RandMac return type  object incompatible with subprocess module. 

### ISSUE THREAD

**Issue by Zaidtech** [joshschmelzle/randomizemac#1]
The Obj of RandMac type is incompatible with the subprocess module. Would be handy if returned as a string.

**Comment by Zaidtech** [comment]
@joshschmelzle sir, please look into it.

**Comment by joshschmelzle** [comment]
@Zaidtech can you give me an example of how you're using it with the subprocess module?

**Comment by Zaidtech** [comment]
@joshschmelzle I tried to change the mac address of my device by passing it like this

`(subprocess.run(['ifconfig', '*******', 'hw', 'ether', str(mac)]))`

**Comment by joshschmelzle** [comment]
@Zaidtech try something like this:

```
>>> subprocess.run(['ifconfig', 'wlan1', 'hw', 'ether', str(randmac.RandMac())])
SIOCSIFHWADDR: Operation not permitted
CompletedProcess(args=['ifconfig', 'wlan1', 'hw', 'ether', '42:fd:ea:fd:f6:91'], returncode=1)
```

**Comment by Zaidtech** [comment]
@joshschmelzle  Ok, thanks sir .. let me try this
